### PR TITLE
Bugfix: show source tags if not lazyloading

### LINKED ISSUE #25: No Tags available if not lazy loading
When not Lazy Loading, for pages with tags, the list displays all the avilable tags.  For new pages with no tags the list is empty.  Turning on lazy loading fixes this. 

````
    $field = new TagField(
      'RelationTags', 'Nursing, Corporate etc', Tag::get(), $this->RelationTags()
    );
//    $field->setShouldLazyLoad(true); // uncomment to workaround
    $field->setCanCreate(true);      // new tag DataObjects can be created
````

### PR DESCRIPTION
**Pull request by micschk**
Fixes #25: no source tags would be shown if not lazy loading (on new records/records without any pre-selected tags)

### CODE REVIEW

**Comment by tractorcow** [comment]
Good fix, but the tests are broken due to reliance on hard coded DB ids (which is a flaw in the test design, to be honest).

In any case, this change will need a unit test. :) How confident do you feel in writing one?

You can soft-code the test fixture ids with `$id = $this->idFromFixture('TagFieldTestBlogTag', 'Tag1)`; etc

**Comment by micschk** [comment]
Writing tests is on my should-be-doing-when-i-find-the-time list, I'll add
this one :)

So, I'll do it eventually -- may take a while though (sorry).

**Comment by dhensby** [comment]
assuming #70 passes and gets merged, this will either need a re-base or the CI tests restarting

**Comment by dhensby** [comment]
tests pass now that #70 is merged

**Pull request merged**
