### PR TITLE
Added option to disable multiple selections.

### PR DESCRIPTION
**Pull request by mediabeastnz**
Added option to disable multiple selections.

E.g. 
```php
StringTagField::create()->setIsMultiple(false)
```

This combined with `->setAttribute("data-multiple", 0)` makes it work like a standard select box but with search.

### CODE REVIEW

**Comment by assertchris** [comment]
thank you, sir!

**Comment by mediabeastnz** [comment]
Hey Chris, git noob question - how do i push to this pull request?? on StringTagField theres two `setAttribute("multiple")` which was my bad! 

Will push a fix now but was trying not to make another PR.

**Comment by assertchris** [comment]
Haha, you can't. I should have checked that.

**Comment by mediabeastnz** [comment]
I should have triple checked! Apologies.

**Pull request merged**
