### PR TITLE
FIX Added the state changed checks and bubble up event

### PR DESCRIPTION
**Pull request by josephlewisnz**
Note that this should not cause regressions for:
- https://github.com/silverstripe/silverstripe-tagfield/issues/125
- https://github.com/silverstripe/silverstripe-tagfield/issues/247

## Issue
- https://github.com/silverstripe/silverstripe-tagfield/issues/260

### CODE REVIEW

**Comment by josephlewisnz** [comment]
I tried to keep the PR inline as close to the branch 3
https://github.com/silverstripe/silverstripe-tagfield/pull/251/files

This branch (2) is using older version of react + node.
I didn't upgrade them so the there are slight changes in the approach

**Comment by GuySartorelli** [comment]
Thank you for submitting this PR.

In order for us to release this, it needs to be targetting the correct branch. The `2` branch would be used if we were to release this in a new minor release, but we aren't making new minor releases for the `2.x` release line.
Please retarget this PR to the `2.11` branch, and [reset your commits](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f) afterwards if necessary.

**Comment by josephlewisnz** [comment]
Thanks @GuySartorelli  - Just running through the reset steps

**Comment by josephlewisnz** [comment]
@GuySartorelli I believe I have done that correctly..

**Comment by GuySartorelli** [comment]
Awesome, thank you. Looks correct to me. Someone will review this as time permits.

**Review by sabina-talipova — APPROVED** [review]
Looks good to me. 
Test locally, all works perfect.

**Pull request merged**
