### PR TITLE
Remove unnecessary react-select scss import that breaks other CMS styles

### LINKED ISSUE #211: Breaks TreeMultiselectField CSS Styles
Styles applied by the `TagField` module seem to negatively effect the styles for instances of `TreeMultiselectField`.

e.g.:
`TreeMultiselectField` **without** `TagField` installed:
Screenshot 2022-06-08 at 14 22 53@2x

`TreeMultiselectField` **with** `TagField` installed:
Screenshot 2022-06-08 at 14 27 18@2x

### PR DESCRIPTION
**Pull request by purplespider**
Fixes #211 

**Before:**
Screenshot 2022-12-22 at 10 15 54@2x
Screenshot 2022-12-22 at 10 18 04@2x

**After:**
Screenshot 2022-12-22 at 10 21 16@2x
Screenshot 2022-12-22 at 10 20 26@2x

### CODE REVIEW

**Comment by michalkleiner** [comment]
How do focused and hovered tags look before and after?

**Comment by purplespider** [comment]
The same as the built in `TreeMultiselectField`:

Screenshot 2022-12-22 at 10 35 49@2x

And here's the dropdown, again the same as the standard `TreeMultiselectField`:
Screenshot 2022-12-22 at 10 40 26@2x

**Review by GuySartorelli — APPROVED** [review]

**Comment by GuySartorelli** [comment]
Seems fine to me but I wouldn't mind someone else giving this a quick once-over in case I have missed something

**Comment by purplespider** [comment]
Good to merge?

**Comment by GuySartorelli** [comment]
I was hoping someone else would take a look but it seems like that's not happening so yeah I'll merge.
Thanks for doing this!

**Comment by GuySartorelli** [comment]
Oops, and as soon as I merge it I realise this should target `2.0` to make it for launch. Doh. I'll backport it.

**Pull request merged**
