### PR TITLE
Added license to composer.json

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. This one special repository has changed licenses. I have special knowledge of this. Special robotic knowledge.

Have a nice day! [brrrrrmmm]

### CODE REVIEW

**Comment by dhensby** [comment]
Probably the wrong place to ask, but why is this module MIT? I thought all supported modules had to be BSD...

**Comment by hafriedlander** [comment]
From wikipedia: The MIT License is similar to the 3-clause "modified" BSD license, except that the BSD license contains a notice prohibiting the use of the name of the copyright holder in promotion. 

They're nearly entirely interchangable.

(There's some confusion between "Old BSD" (not GPL compatible) and "New / modified BSD" (GPL compatible).

**Comment by dhensby** [comment]
Ah, I thought MIT was "original copyright owner owns your changes" - I was mistaken

**Comment by dhensby** [comment]
so problem now is the licence IS 3-clause-bsd

**Comment by assertchris** [comment]
@helpfulrobot UPDATE THIS DAMN LICENSE!

**Comment by dhensby** [comment]
ping @helpfulrobot

**Comment by dhensby** [comment]
DO I HAVE TO SPELL IT OUT TO YOU @helpfulrobot 

[beepty boop bop pop boop bap booby bap poop]!!!

**Comment by dhensby** [comment]
that's right

**Pull request merged**
